"""Dataset seed cho mô hình phân loại danh mục giao dịch (data card).

**Mục đích:** dữ liệu huấn luyện cho ``categorizer`` (TF-IDF + Logistic Regression) — gợi ý danh mục
từ ghi chú giao dịch tiếng Việt.

**Nhãn (7):** Ăn uống · Đi lại · Mua sắm · Hoá đơn · Giải trí · Sức khoẻ · Lương.

**Nguồn:** team tự tuyển chọn (~16 ví dụ/nhãn), ghi chú tiếng Việt tự nhiên trong miền chi tiêu cá
nhân; cố ý vượt ra ngoài bộ từ khoá của rule baseline để mô hình học khái quát.

**Hạn chế:** bộ nhỏ, chỉ tiếng Việt, miền chi tiêu cá nhân; "Khác" KHÔNG phải nhãn huấn luyện mà
là fallback khi mô hình/độ tự tin thấp (xem ``categorizer.suggest_category``). Mở rộng dần khi có
dữ liệu giao dịch thật + nhãn.
"""

from __future__ import annotations

CATEGORIES: tuple[str, ...] = (
    "Ăn uống",
    "Đi lại",
    "Mua sắm",
    "Hoá đơn",
    "Giải trí",
    "Sức khoẻ",
    "Lương",
)

# (ghi chú, nhãn) — thứ tự không quan trọng; giữ đa dạng cách diễn đạt (~28 mẫu/nhãn).
TRAINING_DATA: list[tuple[str, str]] = [
    # Ăn uống
    ("ăn trưa cùng team", "Ăn uống"),
    ("cơm tấm sườn bì chả", "Ăn uống"),
    ("bún bò huế", "Ăn uống"),
    ("phở gà buổi sáng", "Ăn uống"),
    ("ăn sáng phở bò", "Ăn uống"),
    ("trà sữa trân châu đường đen", "Ăn uống"),
    ("cà phê sữa đá vỉa hè", "Ăn uống"),
    ("ăn tối nhà hàng nhật", "Ăn uống"),
    ("bánh mì thịt nướng", "Ăn uống"),
    ("lẩu thái cuối tuần", "Ăn uống"),
    ("pizza giao tận nơi", "Ăn uống"),
    ("cơm văn phòng buổi trưa", "Ăn uống"),
    ("buffet hải sản", "Ăn uống"),
    ("nước mía giải khát", "Ăn uống"),
    ("hủ tiếu nam vang", "Ăn uống"),
    ("gỏi cuốn tôm thịt", "Ăn uống"),
    ("chè khúc bạch tráng miệng", "Ăn uống"),
    ("kem tươi cuối buổi", "Ăn uống"),
    ("bánh tráng trộn vỉa hè", "Ăn uống"),
    ("xôi gà ăn sáng", "Ăn uống"),
    ("mì cay hàn quốc", "Ăn uống"),
    ("cơm gà xối mỡ", "Ăn uống"),
    ("sinh tố bơ mát lạnh", "Ăn uống"),
    ("bánh canh cua", "Ăn uống"),
    ("ốc luộc buổi tối", "Ăn uống"),
    ("sữa chua nếp cẩm", "Ăn uống"),
    ("trà chanh giải khát", "Ăn uống"),
    ("cháo sườn nóng", "Ăn uống"),
    # Đi lại
    ("đi grab về nhà", "Đi lại"),
    ("đổ xăng xe máy", "Đi lại"),
    ("gửi xe tháng chung cư", "Đi lại"),
    ("vé xe buýt đi làm", "Đi lại"),
    ("taxi ra sân bay", "Đi lại"),
    ("đặt gojek đi học", "Đi lại"),
    ("tiền xăng tuần này", "Đi lại"),
    ("vé tàu hoả về quê", "Đi lại"),
    ("thuê xe tự lái", "Đi lại"),
    ("phí cầu đường cao tốc", "Đi lại"),
    ("đặt be đi gặp khách", "Đi lại"),
    ("rửa xe máy", "Đi lại"),
    ("bảo dưỡng xe định kỳ", "Đi lại"),
    ("vé máy bay nội địa", "Đi lại"),
    ("xe ôm công nghệ", "Đi lại"),
    ("vá lốp xe giữa đường", "Đi lại"),
    ("nạp thẻ xe buýt", "Đi lại"),
    ("phí đỗ ô tô trung tâm", "Đi lại"),
    ("thuê xe đạp công cộng", "Đi lại"),
    ("đi xe ghép về quê", "Đi lại"),
    ("tiền dầu ô tô", "Đi lại"),
    ("vé phà qua sông", "Đi lại"),
    ("đi tàu điện trên cao", "Đi lại"),
    ("thay nhớt xe máy", "Đi lại"),
    ("cuốc grab bike buổi trưa", "Đi lại"),
    ("đặt xe đi sân bay", "Đi lại"),
    ("phí giữ xe bệnh viện", "Đi lại"),
    ("vé tàu cao tốc", "Đi lại"),
    # Mua sắm
    ("mua áo trên shopee", "Mua sắm"),
    ("đặt hàng lazada sale", "Mua sắm"),
    ("giày thể thao mới", "Mua sắm"),
    ("quần jean ống rộng", "Mua sắm"),
    ("mỹ phẩm trên tiki", "Mua sắm"),
    ("túi xách da thật", "Mua sắm"),
    ("đồ gia dụng nhà bếp", "Mua sắm"),
    ("kem dưỡng da ban đêm", "Mua sắm"),
    ("đồng hồ đeo tay", "Mua sắm"),
    ("balo đi học cho con", "Mua sắm"),
    ("nồi chiên không dầu", "Mua sắm"),
    ("áo khoác mùa đông", "Mua sắm"),
    ("tai nghe bluetooth", "Mua sắm"),
    ("son môi hàng hiệu", "Mua sắm"),
    ("mua sách tiểu thuyết", "Mua sắm"),
    ("bàn phím cơ", "Mua sắm"),
    ("mua chậu cây cảnh", "Mua sắm"),
    ("bộ chén bát sứ", "Mua sắm"),
    ("rèm cửa phòng khách", "Mua sắm"),
    ("chăn ga gối đệm", "Mua sắm"),
    ("máy sấy tóc", "Mua sắm"),
    ("bình giữ nhiệt", "Mua sắm"),
    ("dao kéo nhà bếp", "Mua sắm"),
    ("đèn ngủ để bàn", "Mua sắm"),
    ("thảm trải sàn phòng khách", "Mua sắm"),
    ("kệ sách bằng gỗ", "Mua sắm"),
    ("ô dù đi mưa", "Mua sắm"),
    ("ví da nam cầm tay", "Mua sắm"),
    # Hoá đơn
    ("tiền điện tháng 6", "Hoá đơn"),
    ("hoá đơn nước sinh hoạt", "Hoá đơn"),
    ("cước internet cáp quang", "Hoá đơn"),
    ("wifi nhà mạng", "Hoá đơn"),
    ("tiền nhà tháng này", "Hoá đơn"),
    ("thuê phòng trọ", "Hoá đơn"),
    ("hoá đơn điện thoại", "Hoá đơn"),
    ("phí quản lý chung cư", "Hoá đơn"),
    ("tiền gas nấu ăn", "Hoá đơn"),
    ("truyền hình cáp", "Hoá đơn"),
    ("đóng tiền điện hàng tháng", "Hoá đơn"),
    ("cước di động trả sau", "Hoá đơn"),
    ("tiền thuê mặt bằng", "Hoá đơn"),
    ("phí thu gom rác", "Hoá đơn"),
    ("tiền nước máy", "Hoá đơn"),
    ("gia hạn tên miền website", "Hoá đơn"),
    ("nạp tiền điện thoại trả trước", "Hoá đơn"),
    ("phí thường niên ngân hàng", "Hoá đơn"),
    ("đóng học phí cho con", "Hoá đơn"),
    ("đóng bảo hiểm xe ô tô", "Hoá đơn"),
    ("tiền nước uống bình", "Hoá đơn"),
    ("cước truyền hình k cộng", "Hoá đơn"),
    ("tiền điện điều hoà mùa hè", "Hoá đơn"),
    ("phí sửa ống nước", "Hoá đơn"),
    ("phí vệ sinh môi trường", "Hoá đơn"),
    ("tiền thuê kho hàng", "Hoá đơn"),
    ("hoá đơn gas công nghiệp", "Hoá đơn"),
    ("phí dịch vụ căn hộ", "Hoá đơn"),
    # Giải trí
    ("vé xem phim cuối tuần", "Giải trí"),
    ("đăng ký netflix gói tháng", "Giải trí"),
    ("nạp thẻ game online", "Giải trí"),
    ("spotify premium", "Giải trí"),
    ("du lịch đà lạt", "Giải trí"),
    ("vé concert tối nay", "Giải trí"),
    ("đi bar với bạn bè", "Giải trí"),
    ("thuê sân bóng đá", "Giải trí"),
    ("vé sở thú cho cả nhà", "Giải trí"),
    ("đặt phòng khách sạn nghỉ dưỡng", "Giải trí"),
    ("karaoke cuối tuần", "Giải trí"),
    ("youtube premium", "Giải trí"),
    ("vé công viên nước", "Giải trí"),
    ("board game cafe", "Giải trí"),
    ("đi xem kịch sân khấu", "Giải trí"),
    ("vé ca nhạc liveshow", "Giải trí"),
    ("vé bảo tàng mỹ thuật", "Giải trí"),
    ("mua vé xiếc thiếu nhi", "Giải trí"),
    ("đi câu cá thư giãn", "Giải trí"),
    ("vé leo núi nhân tạo", "Giải trí"),
    ("tiền cắm trại cuối tuần", "Giải trí"),
    ("vé hồ bơi mùa hè", "Giải trí"),
    ("vé trượt patin", "Giải trí"),
    ("đi đánh golf cuối tuần", "Giải trí"),
    ("vé đua go kart", "Giải trí"),
    ("đặt tour du lịch biển", "Giải trí"),
    ("đi bowling với đồng nghiệp", "Giải trí"),
    ("phí thành viên câu lạc bộ", "Giải trí"),
    # Sức khoẻ
    ("mua thuốc cảm cúm", "Sức khoẻ"),
    ("khám tổng quát định kỳ", "Sức khoẻ"),
    ("bệnh viện tái khám", "Sức khoẻ"),
    ("nha khoa lấy cao răng", "Sức khoẻ"),
    ("thuốc bổ vitamin tổng hợp", "Sức khoẻ"),
    ("đi khám da liễu", "Sức khoẻ"),
    ("vật lý trị liệu cột sống", "Sức khoẻ"),
    ("mua khẩu trang y tế", "Sức khoẻ"),
    ("tiêm phòng cúm mùa", "Sức khoẻ"),
    ("phòng khám tư nhân", "Sức khoẻ"),
    ("thuốc kháng sinh", "Sức khoẻ"),
    ("khám mắt đo cận", "Sức khoẻ"),
    ("chữa răng sâu", "Sức khoẻ"),
    ("xét nghiệm máu tổng quát", "Sức khoẻ"),
    ("đo huyết áp tại nhà", "Sức khoẻ"),
    ("mua nước muối sinh lý", "Sức khoẻ"),
    ("máy đo đường huyết", "Sức khoẻ"),
    ("khám thai định kỳ", "Sức khoẻ"),
    ("thuốc ho cho bé", "Sức khoẻ"),
    ("đi spa trị liệu cổ vai", "Sức khoẻ"),
    ("mua nẹp đầu gối", "Sức khoẻ"),
    ("khám tai mũi họng", "Sức khoẻ"),
    ("viện phí nằm viện", "Sức khoẻ"),
    ("mua men tiêu hoá", "Sức khoẻ"),
    ("đo thị lực ở viện", "Sức khoẻ"),
    ("thuốc giảm đau hạ sốt", "Sức khoẻ"),
    ("khám sức khoẻ xin việc", "Sức khoẻ"),
    ("mua nhiệt kế điện tử", "Sức khoẻ"),
    # Lương
    ("nhận lương tháng", "Lương"),
    ("lương tháng 6", "Lương"),
    ("thưởng tết cuối năm", "Lương"),
    ("thưởng dự án hoàn thành", "Lương"),
    ("lương cứng hàng tháng", "Lương"),
    ("phụ cấp ăn trưa công ty", "Lương"),
    ("tiền thưởng kpi quý", "Lương"),
    ("lương tăng ca cuối tháng", "Lương"),
    ("thu nhập freelance", "Lương"),
    ("thưởng hiệu suất công việc", "Lương"),
    ("lương part time", "Lương"),
    ("hoa hồng bán hàng", "Lương"),
    ("lương tháng 13", "Lương"),
    ("thưởng nóng cuối dự án", "Lương"),
    ("nhận thưởng quý 2", "Lương"),
    ("lương cộng tác viên", "Lương"),
    ("tiền lương về tài khoản", "Lương"),
    ("thưởng chuyên cần", "Lương"),
    ("lương thử việc nhân viên mới", "Lương"),
    ("tiền tăng lương đợt mới", "Lương"),
    ("thu nhập dạy thêm buổi tối", "Lương"),
    ("thưởng doanh số tháng", "Lương"),
    ("lương dự án ngoài", "Lương"),
    ("tiền công làm thêm giờ", "Lương"),
    ("thưởng giới thiệu nhân sự", "Lương"),
    ("lương vị trí quản lý", "Lương"),
    ("tiền thưởng lễ tết", "Lương"),
    ("nhận lương qua chuyển khoản", "Lương"),
]
