"""add recurring_rules

Revision ID: f8dc0ceb6d66
Revises: 5fb2d5eb9124
Create Date: 2026-06-09 09:16:19.591250

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8dc0ceb6d66"
down_revision: str | Sequence[str] | None = "5fb2d5eb9124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("category_name", sa.String(length=255), nullable=False),
        sa.Column("wallet_id", sa.String(length=36), nullable=True),
        sa.Column("frequency", sa.String(length=8), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("next_run", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recurring_rules_space_id"), ["space_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recurring_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recurring_rules_space_id"))

    op.drop_table("recurring_rules")
    # ### end Alembic commands ###
